import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import Header from '@/components/Header';
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden bg-white dark:bg-gray-900`}
      >
        <Header />
        <Navbar />
        <main className="flex-1 max-w-screen-md w-full mx-auto px-4 pt-[5rem] pb-[4.75rem] md:pt-[6rem] md:pb-[4rem]">
          {children}
        </main>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
